---
title: "Decision Tree"
output: html_notebook
---

This example is taken from
https://data-flair.training/blogs/r-decision-trees/


```{r}
install.packages('party')
install.packages('partykit')
library(rpart)
library(readr)
library(caTools)
library(dplyr)
library(party)
library(partykit)
library(rpart.plot)
```
After this, we will read our data and store it inside the titanic_data variable.

```{r}
titanic_data <- "https://goo.gl/At238b" %>%  #DataFlair
  read.csv %>% # read in the data
  select(survived, embarked, sex, 
         sibsp, parch, fare) %>%
  mutate(embarked = factor(embarked),
         sex = factor(sex))
```

After this, we will split our data into training and testing sets as follows:

```{r}

set.seed(123)
sample_data = sample.split(titanic_data, SplitRatio = 0.75)
train_data <- subset(titanic_data, sample_data == TRUE)
test_data <- subset(titanic_data, sample_data == FALSE)

```

Train the tree

```{r}
rtree <- rpart(survived~., train_data)
rpart.plot(rtree)
ctree_ <- ctree(survived ~ ., train_data)
plot(ctree_)
```

